name = "keccaky"
version = "1.0.0"
description = "High-performance Keccak (SHA-3) implementation with Gleam interface, providing easy access to Keccak-256 hashing through a Rust backend"
licences = ["MIT"]
repository = { type = "github", user = "pxlvre", repo = "keccaky" }
links = [
  { title = "Repository", href = "https://github.com/pxlvre/keccaky" },
  { title = "Documentation", href = "https://github.com/pxlvre/keccaky#readme" }
]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
